### ISSUE TITLE
Feature Requests: Some useful features available in other apps

### ISSUE THREAD

**Issue by dwettstein** [SimpleMobileTools/Simple-Keyboard#127]
First of all, thank you very much for all your apps. They are just great!

Currently the keyboard is not only simple but also very basic. Here are some useful features that are available in other apps.

- [x] Numpad support (see #93)
- [x] Punctuations as popup menu for period (see #112)
- [ ] Show key borders, toggleable as a setting (see #39)
- [ ] Dedicated number row on top, toggleable as a setting (see #53)
- [ ] Show symbol hints on chars, equally as with the numbers, eventually toggleable as a setting
- [ ] When in symbols or numbers, adding a space switches view to chars
- [ ] Auto-capitalisation first word, toggleable as a setting (see #48)
- [ ] Autospace after punctuation, toggleable as a setting
- [ ] Double-space adds a period (full stop)
- [ ] Swipe on spacebar to move cursor
- [ ] Swipe on delete key to delete multiple chars
- [ ] Long-press spacebar to change input method
- [ ] Resizeable height or font size, percent multiplier as a setting (see #126)
- [ ] Export and import settings, similar as your apps _Simple Gallery_ and _Simple Calendar_

Some inspiration:
- https://github.com/rkkr/simple-keyboard (no emoji support)
- https://github.com/openboard-team/openboard (large installation size)

PS: Feel free to also pin this issue or use the text in the README.

**Comment by tibbi** [comment]
report them one by one, if not reported yet. Thanks
